// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230507013454_tp2")]
    partial class tp2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("float");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega", (string)null);

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "https://imagenes.montevideo.com.uy/imgnoticias/202208/_W640_H364_80/812451.jpeg",
                            Ingredientes = "2 Tostadas, 1 dip de mostaza y ciboulette",
                            Nombre = "Dip de mostaza y ciboulette",
                            Precio = 600.0,
                            Preparacion = "Mezcla crema agria, mostaza dijon y amarilla. Agrega ciboulette picada, sal y pimienta al gusto. Revuelve para obtener una mezcla homogénea.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "https://assets.unileversolutions.com/recipes-v2/239857.jpg",
                            Ingredientes = "Carne, Cebolla, Huevo, Masa casera, Tomate",
                            Nombre = "Empanada de carne",
                            Precio = 320.0,
                            Preparacion = "Se saltea la cebolla, luego se agrega la carne junto al tomate y se cocina por 10 minutos, se agregan especias y el huevo. Se arma la empanada y se repulga. Luego se cocinan hasta estar bien doradas.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "https://i.blogs.es/1cf6bd/milanesa-napolitana-min/1366_2000.jpeg",
                            Ingredientes = "Milanesa, queso muzzarela, salsa de tomate y oregano",
                            Nombre = "Milanesa a la napolitana",
                            Precio = 1400.0,
                            Preparacion = "La milanesa se cubre con salsa de tomate, queso y oregano, y se hornea para que el queso se derrita",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "https://www.laylita.com/recetas/wp-content/uploads/Receta-del-choripan.jpg",
                            Ingredientes = "Chorizo, pan y salsa a eleccion",
                            Nombre = "Choripan",
                            Precio = 1000.0,
                            Preparacion = "se debe asar una salchicha de chorizo en una parrilla o sartén. Luego, se coloca la salchicha en un pan tipo baguette y se le agrega chimichurri u otras salsas al gusto.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "https://www.clarin.com/img/2018/06/19/HJS8-kvW7_1256x620__2.jpg",
                            Ingredientes = "Ñoquis de papa, salsa filetto",
                            Nombre = "Ñoquis de papa",
                            Precio = 1200.0,
                            Preparacion = "Se cocinan los ñoquis por alrededor de 3 o 4 minutos y luego se le agrega la salsa",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "https://media-cdn.tripadvisor.com/media/photo-s/1a/6b/34/b7/sorrentinos-de-jamon.jpg",
                            Ingredientes = "Jamon, queso y riccota, masa de sorrentinos",
                            Nombre = "Sorrentinos de jamón y queso",
                            Precio = 1800.0,
                            Preparacion = "Se rellena la masa con jamon, queso y ricotta. Luego se cocina por 8-10 minutos aprox ",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://www.gastrotradicional.com/wp-content/uploads/2018/09/como-preparar-asado-a-la-parilla.jpg",
                            Ingredientes = "Diferentes cortes de carne, como tira de asado, vacío, matambre, chorizo y morcilla",
                            Nombre = "Asado",
                            Precio = 2000.0,
                            Preparacion = "Sazonados con sal, los cortes de carne se cocinan a fuego lento en la parrilla",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "https://www.comedera.com/wp-content/uploads/2022/06/bife-de-chorizo.jpg",
                            Ingredientes = "Bife de chorizo",
                            Nombre = "Bife de Chorizo",
                            Precio = 600.0,
                            Preparacion = "El bife de chorizo se cocina a la parrilla, a fuego medio, para que quede jugoso y tierno",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://rankea.com.ar/wp-content/uploads/2019/05/pizza-muzzarella.jpg",
                            Ingredientes = "Harina, agua, sal, aceite, Salsa de tomate, Mozzarella",
                            Nombre = "Pizza de mozzarella",
                            Precio = 1500.0,
                            Preparacion = "Se prepara la masa de pizza. Se deje elevar. Se estira la masa en las pizzeras, luego se agrega la salsa, metemos al horno unos minutos. Luego se agrega la mozzarella y se cocina al horno a 220 °C durante 15 min",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://resizer.glanacion.com/resizer/TZzg6LYEvQpEof1TshBXqEspVYE=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/X6FSNA3BJBF7XB36HEECQGYS7Y.jpg",
                            Ingredientes = "Harina, agua, sal, aceite, cebolla, jamon y mozzarella",
                            Nombre = "Fuggazzeta rellena",
                            Precio = 3400.0,
                            Preparacion = "Preparar la masa, armar la fugazzetta y hornear la fugazzetta",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://www.allrecipes.com/thmb/4tHUrnO9xe0CBPli8Tmjm4ydaq8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8338654_Torta-de-Milanesa-de-Pollo-4x3-1-739b7387043144f6b848abcc872be181.jpg",
                            Ingredientes = "Milanesa de pollo, pan ",
                            Nombre = "Sandwich de milanesa de pollo",
                            Precio = 1000.0,
                            Preparacion = "Se cocina la milanesa y luego se le agrega el pan",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://d3ugyf2ht6aenh.cloudfront.net/stores/288/056/products/simples31-743189307744419c7d15119397744217-640-0.jpg",
                            Ingredientes = "Jamon, Queso, Capas de pan de miga blanco sin corteza",
                            Nombre = "Sandwich de miga de jamon y queso",
                            Precio = 400.0,
                            Preparacion = "Se rellena el pan con jamon y queso",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "https://www.cocinacaserayfacil.net/wp-content/uploads/2018/06/Ensalada-cesar.jpg",
                            Ingredientes = "Lechuga romana, pollo a la parrilla, crutones, queso parmesano rallado y aderezo César ",
                            Nombre = "Ensalada Caesar",
                            Precio = 1200.0,
                            Preparacion = "La ensalada Caesar se prepara mezclando lechuga romana fresca, croutones de pan tostado, queso parmesano rallado y una salsa especial hecha con aceite de oliva, yema de huevo, anchoas, ajo y mostaza.",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://www.hogarmania.com/archivos/201606/5800-2-ensalada-de-rucula-cherrys-y-queso-xl-1280x720x80xX.jpg",
                            Ingredientes = "Base de rúcula, tomates cherry, láminas de parmesano, aceite de oliva y aceto balsámico",
                            Nombre = "Ensalada de rúcula",
                            Precio = 1200.0,
                            Preparacion = "Para preparar una ensalada de rúcula, lava y seca la rúcula, añade aceite de oliva y vinagre balsámico al gusto, y decora con queso parmesano y piñones tostados.",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg/320px-15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg",
                            Ingredientes = "Coca-Cola",
                            Nombre = "Coca-Cola",
                            Precio = 600.0,
                            Preparacion = "La preparación de Coca-Cola implica mezclar agua carbonatada con jarabe de sabor y colorantes caramelo. Luego, se agrega ácido fosfórico y se embotella para su distribución.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://www.distribuidoraniki.com.ar/database/articulos/fotos/346/Fanta%20Naranja%20Retornable%20350cc%20vidrio%20ret__1.jpg",
                            Ingredientes = "Fanta",
                            Nombre = "Fanta",
                            Precio = 600.0,
                            Preparacion = "La preparación de Fanta implica mezclar agua carbonatada con jarabe de sabores y colorantes. La proporción exacta de ingredientes puede variar según la receta y el sabor deseado. Luego, se embotella y se distribuye para su consumo.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://www.clarin.com/img/2020/08/18/PY22-FZSu_1256x620__2.jpg#1628113269253",
                            Ingredientes = "Cerveza Artesanal IPA",
                            Nombre = "Pinta de IPA",
                            Precio = 1000.0,
                            Preparacion = " implica la molienda de granos de malta, la maceración en agua caliente para obtener azúcares fermentables, la adición de lúpulo durante la ebullición, la fermentación con levadura y el embotellado o barrilado para la carbonatación.",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/246/405/products/a-0511-a33b3f8f516d7f17ec15940544201315-640-0.jpg",
                            Ingredientes = "Cerveza Artesanal Honey",
                            Nombre = "Pinta de Honey",
                            Precio = 1000.0,
                            Preparacion = "La cerveza artesanal honey se prepara agregando miel durante el proceso de elaboración. La miel se añade en el momento de la cocción del mosto y luego se fermenta con levadura y otros ingredientes como lúpulo y malta",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://cocinerosargentinos.com/content/recipes/500x500/recipes.14669.jpeg",
                            Ingredientes = "Huevos, leche y azucar",
                            Nombre = "Flan Casero",
                            Precio = 1200.0,
                            Preparacion = "Para preparar el flan, se baten los huevos y se mezclan con la leche y el azúcar, y se cuece esta mezcla en un molde con caramelo líquido en baño María. Una vez que se ha enfriado y se ha solidificado, se desmolda y se sirve.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/09/14170007/chocotorta-destacada.jpg",
                            Ingredientes = "Galletas de chocolate, dulce de leche, queso crema, cafe fuerte",
                            Nombre = "Chocotorta",
                            Precio = 1500.0,
                            Preparacion = "Preparar la crema, luego armar las capas y por ultimo refrigerar y decorar",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comanda")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderia")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderia");
                });
#pragma warning restore 612, 618
        }
    }
}
