using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infraestructure.Persistence.Mappings
{
    public class MercaderiaMappings : IEntityTypeConfiguration<Mercaderia>
    {
        public void Configure(EntityTypeBuilder<Mercaderia> entityBuilder)
        {
            entityBuilder.ToTable("Mercaderia");
            entityBuilder.HasKey(m => m.MercaderiaId);
            entityBuilder.HasMany(m => m.ComandaMercaderia).WithOne(cm => cm.Mercaderia).IsRequired();

            entityBuilder.Property(p => p.MercaderiaId).ValueGeneratedOnAdd().IsRequired();
            entityBuilder.Property(p => p.Nombre).HasMaxLength(50).HasColumnType("nvarchar").IsRequired();
            entityBuilder.Property(p => p.Ingredientes).HasMaxLength(255).HasColumnType("nvarchar").IsRequired();
            entityBuilder.Property(p => p.Preparacion).HasMaxLength(255).HasColumnType("nvarchar").IsRequired();
            entityBuilder.Property(p => p.Imagen).HasMaxLength(255).HasColumnType("nvarchar").IsRequired();
            entityBuilder.Property(p => p.TipoMercaderiaId).IsRequired();
            entityBuilder.Property(p => p.Precio).IsRequired();

            entityBuilder.HasData
                (
                    new Mercaderia { MercaderiaId = 1, TipoMercaderiaId = 1, Nombre = "Dip de mostaza y ciboulette", Precio = 600, Ingredientes = "2 Tostadas, 1 dip de mostaza y ciboulette", Preparacion = "Mezcla crema agria, mostaza dijon y amarilla. Agrega ciboulette picada, sal y pimienta al gusto. Revuelve para obtener una mezcla homogénea.", Imagen = "https://imagenes.montevideo.com.uy/imgnoticias/202208/_W640_H364_80/812451.jpeg" },
                    new Mercaderia { MercaderiaId = 2, TipoMercaderiaId = 1, Nombre = "Empanada de carne", Precio = 320, Ingredientes = "Carne, Cebolla, Huevo, Masa casera, Tomate", Preparacion = "Se saltea la cebolla, luego se agrega la carne junto al tomate y se cocina por 10 minutos, se agregan especias y el huevo. Se arma la empanada y se repulga. Luego se cocinan hasta estar bien doradas.", Imagen = "https://assets.unileversolutions.com/recipes-v2/239857.jpg" },
                    new Mercaderia { MercaderiaId = 3, TipoMercaderiaId = 2, Nombre = "Milanesa a la napolitana", Precio = 1400, Ingredientes = "Milanesa, queso muzzarela, salsa de tomate y oregano", Preparacion = "La milanesa se cubre con salsa de tomate, queso y oregano, y se hornea para que el queso se derrita", Imagen = "https://i.blogs.es/1cf6bd/milanesa-napolitana-min/1366_2000.jpeg" },
                    new Mercaderia { MercaderiaId = 4, TipoMercaderiaId = 2, Nombre = "Choripan", Precio = 1000, Ingredientes = "Chorizo, pan y salsa a eleccion", Preparacion = "se debe asar una salchicha de chorizo en una parrilla o sartén. Luego, se coloca la salchicha en un pan tipo baguette y se le agrega chimichurri u otras salsas al gusto.", Imagen = "https://www.laylita.com/recetas/wp-content/uploads/Receta-del-choripan.jpg" },
                    new Mercaderia { MercaderiaId = 5, TipoMercaderiaId = 3, Nombre = "Ñoquis de papa", Precio = 1200, Ingredientes = "Ñoquis de papa, salsa filetto", Preparacion = "Se cocinan los ñoquis por alrededor de 3 o 4 minutos y luego se le agrega la salsa", Imagen = "https://www.clarin.com/img/2018/06/19/HJS8-kvW7_1256x620__2.jpg" },
                    new Mercaderia { MercaderiaId = 6, TipoMercaderiaId = 3, Nombre = "Sorrentinos de jamón y queso", Precio = 1800, Ingredientes = "Jamon, queso y riccota, masa de sorrentinos", Preparacion = "Se rellena la masa con jamon, queso y ricotta. Luego se cocina por 8-10 minutos aprox ", Imagen = "https://media-cdn.tripadvisor.com/media/photo-s/1a/6b/34/b7/sorrentinos-de-jamon.jpg" },
                    new Mercaderia { MercaderiaId = 7, TipoMercaderiaId = 4, Nombre = "Asado", Precio = 2000, Ingredientes = "Diferentes cortes de carne, como tira de asado, vacío, matambre, chorizo y morcilla", Preparacion = "Sazonados con sal, los cortes de carne se cocinan a fuego lento en la parrilla", Imagen = "https://www.gastrotradicional.com/wp-content/uploads/2018/09/como-preparar-asado-a-la-parilla.jpg" },
                    new Mercaderia { MercaderiaId = 8, TipoMercaderiaId = 4, Nombre = "Bife de Chorizo", Precio = 600, Ingredientes = "Bife de chorizo", Preparacion = "El bife de chorizo se cocina a la parrilla, a fuego medio, para que quede jugoso y tierno", Imagen = "https://www.comedera.com/wp-content/uploads/2022/06/bife-de-chorizo.jpg" },
                    new Mercaderia { MercaderiaId = 9, TipoMercaderiaId = 5, Nombre = "Pizza de mozzarella", Precio = 1500, Ingredientes = "Harina, agua, sal, aceite, Salsa de tomate, Mozzarella", Preparacion = "Se prepara la masa de pizza. Se deje elevar. Se estira la masa en las pizzeras, luego se agrega la salsa, metemos al horno unos minutos. Luego se agrega la mozzarella y se cocina al horno a 220 °C durante 15 min", Imagen = "https://rankea.com.ar/wp-content/uploads/2019/05/pizza-muzzarella.jpg" },
                    new Mercaderia { MercaderiaId = 10, TipoMercaderiaId = 5, Nombre = "Fuggazzeta rellena", Precio = 3400, Ingredientes = "Harina, agua, sal, aceite, cebolla, jamon y mozzarella", Preparacion = "Preparar la masa, armar la fugazzetta y hornear la fugazzetta", Imagen = "https://resizer.glanacion.com/resizer/TZzg6LYEvQpEof1TshBXqEspVYE=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/X6FSNA3BJBF7XB36HEECQGYS7Y.jpg" },
                    new Mercaderia { MercaderiaId = 11, TipoMercaderiaId = 6, Nombre = "Sandwich de milanesa de pollo", Precio = 1000, Ingredientes = "Milanesa de pollo, pan ", Preparacion = "Se cocina la milanesa y luego se le agrega el pan", Imagen = "https://www.allrecipes.com/thmb/4tHUrnO9xe0CBPli8Tmjm4ydaq8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8338654_Torta-de-Milanesa-de-Pollo-4x3-1-739b7387043144f6b848abcc872be181.jpg" },
                    new Mercaderia { MercaderiaId = 12, TipoMercaderiaId = 6, Nombre = "Sandwich de miga de jamon y queso", Precio = 400, Ingredientes = "Jamon, Queso, Capas de pan de miga blanco sin corteza", Preparacion = "Se rellena el pan con jamon y queso", Imagen = "https://d3ugyf2ht6aenh.cloudfront.net/stores/288/056/products/simples31-743189307744419c7d15119397744217-640-0.jpg" },
                    new Mercaderia { MercaderiaId = 13, TipoMercaderiaId = 7, Nombre = "Ensalada Caesar", Precio = 1200, Ingredientes = "Lechuga romana, pollo a la parrilla, crutones, queso parmesano rallado y aderezo César ", Preparacion = "La ensalada Caesar se prepara mezclando lechuga romana fresca, croutones de pan tostado, queso parmesano rallado y una salsa especial hecha con aceite de oliva, yema de huevo, anchoas, ajo y mostaza.", Imagen = "https://www.cocinacaserayfacil.net/wp-content/uploads/2018/06/Ensalada-cesar.jpg" },
                    new Mercaderia { MercaderiaId = 14, TipoMercaderiaId = 7, Nombre = "Ensalada de rúcula", Precio = 1200, Ingredientes = "Base de rúcula, tomates cherry, láminas de parmesano, aceite de oliva y aceto balsámico", Preparacion = "Para preparar una ensalada de rúcula, lava y seca la rúcula, añade aceite de oliva y vinagre balsámico al gusto, y decora con queso parmesano y piñones tostados.", Imagen = "https://www.hogarmania.com/archivos/201606/5800-2-ensalada-de-rucula-cherrys-y-queso-xl-1280x720x80xX.jpg" },
                    new Mercaderia { MercaderiaId = 15, TipoMercaderiaId = 8, Nombre = "Coca-Cola", Precio = 600, Ingredientes = "Coca-Cola", Preparacion = "La preparación de Coca-Cola implica mezclar agua carbonatada con jarabe de sabor y colorantes caramelo. Luego, se agrega ácido fosfórico y se embotella para su distribución.", Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg/320px-15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg" },
                    new Mercaderia { MercaderiaId = 16, TipoMercaderiaId = 8, Nombre = "Fanta", Precio = 600, Ingredientes = "Fanta", Preparacion = "La preparación de Fanta implica mezclar agua carbonatada con jarabe de sabores y colorantes. La proporción exacta de ingredientes puede variar según la receta y el sabor deseado. Luego, se embotella y se distribuye para su consumo.", Imagen = "https://www.distribuidoraniki.com.ar/database/articulos/fotos/346/Fanta%20Naranja%20Retornable%20350cc%20vidrio%20ret__1.jpg" },
                    new Mercaderia { MercaderiaId = 17, TipoMercaderiaId = 9, Nombre = "Pinta de IPA", Precio = 1000, Ingredientes = "Cerveza Artesanal IPA", Preparacion = " implica la molienda de granos de malta, la maceración en agua caliente para obtener azúcares fermentables, la adición de lúpulo durante la ebullición, la fermentación con levadura y el embotellado o barrilado para la carbonatación.", Imagen = "https://www.clarin.com/img/2020/08/18/PY22-FZSu_1256x620__2.jpg#1628113269253" },
                    new Mercaderia { MercaderiaId = 18, TipoMercaderiaId = 9, Nombre = "Pinta de Honey", Precio = 1000, Ingredientes = "Cerveza Artesanal Honey", Preparacion = "La cerveza artesanal honey se prepara agregando miel durante el proceso de elaboración. La miel se añade en el momento de la cocción del mosto y luego se fermenta con levadura y otros ingredientes como lúpulo y malta", Imagen = "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/246/405/products/a-0511-a33b3f8f516d7f17ec15940544201315-640-0.jpg" },
                    new Mercaderia { MercaderiaId = 19, TipoMercaderiaId = 10, Nombre = "Flan Casero", Precio = 1200, Ingredientes = "Huevos, leche y azucar", Preparacion = "Para preparar el flan, se baten los huevos y se mezclan con la leche y el azúcar, y se cuece esta mezcla en un molde con caramelo líquido en baño María. Una vez que se ha enfriado y se ha solidificado, se desmolda y se sirve.", Imagen = "https://cocinerosargentinos.com/content/recipes/500x500/recipes.14669.jpeg" },
                    new Mercaderia { MercaderiaId = 20, TipoMercaderiaId = 10, Nombre = "Chocotorta", Precio = 1500, Ingredientes = "Galletas de chocolate, dulce de leche, queso crema, cafe fuerte", Preparacion = "Preparar la crema, luego armar las capas y por ultimo refrigerar y decorar", Imagen = "https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/09/14170007/chocotorta-destacada.jpg" }
                );
        }
    }
}
